spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    port: 3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
      aop-patterns: "com.deyi.clock.service.*,com.deyi.clock.service.serviceImpl.*,com.deyi.clock.controller.*,com.deyi.clock.dao.*"
      stat-view-servlet.reset-enable: false
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/logout"
        session-stat-enable: true
        session-stat-max-count: 100
        sessionStatEnable: true
        principal-session-name: "user"
        principal-cookie-name: "sid"
      stat-view-servlet:
        allow: 127.0.0.1
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
      filter:
        filter:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  devtools:
    restart:
      enabled: true
      exclude: static/**
      additional-paths: src/main/java
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
mybatis:
  configuration:
    call-setters-on-nulls: true
    variables:
      table_name: "demo_"
  type-aliases-package: com.deyi.clock.domain
  config-locations: classpath*:mybatis-config.xml
  mapper-locations: classpath*:com/deyi/clock/dao/mapper/*.xml
#pagehelper
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  helperDialect: mysql
  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  #禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: false
  #支持通过Mapper接口参数来传递分页参数
  supportMethodsArguments: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
  params: count=countSql
  #当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
  page-size-zero: true
logging:
  level:
    com.deyi.clock.dao: DEBUG